name: flutter_audio_streaming_example
description: Demonstrates how to use the flutter_audio_streaming plugin.


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_audio_streaming:
    path: ../

  cupertino_icons: ^1.0.3
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
