name: flutter_audio_streaming
description: A Flutter plugin for record or streaming audio by RTMP
version: 1.0.5
homepage: https://github.com/lqmminh/flutter_audio_streaming/tree/master

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.mminh.flutter_audio_streaming
        pluginClass: FlutterAudioStreamingPlugin
      ios:
        pluginClass: FlutterAudioStreamingPlugin

