name: flutter_audio_streaming
description: A Flutter plugin for record or streaming audio by RTMP
version: 1.0.5
homepage: https://github.com/resideo/flutter_audio_streaming

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.resideo.flutter_audio_streaming
        pluginClass: FlutterAudioStreamingPlugin
      ios:
        pluginClass: FlutterAudioStreamingPlugin

